# Generated by Django 3.0.3 on 2020-04-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_auto_20200423_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
